# Generated by Django 3.0.7 on 2020-07-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotoMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('terminalId', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('loto_machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.LotoMachine')),
            ],
        ),
    ]
